"""Where every solid thing on the site is.

Generated by tools/gen_world.py - do not edit by hand. Regenerating the world
regenerates this too, so the machine can never plan a route through something
that is actually there.

Each entry is (x, y, radius): the radius the machine's centre must stay
outside of, before its own footprint is added.
"""

FENCE = 8.00          # the yard runs from -FENCE to +FENCE on both axes

OBSTACLES = [
    ( -0.640,   7.540, 0.837),   # barrier
    ( -2.640,   7.540, 0.837),   # barrier  (full world only)
    ( -7.540,  -2.330, 0.837),   # barrier  (full world only)
    (  0.460,  -7.540, 0.837),   # barrier  (full world only)
    (  7.540,   0.510, 0.837),   # barrier
    (  7.540,   2.410, 0.837),   # barrier  (full world only)
    (  4.880,  -7.490, 0.546),   # barrow  (full world only)
    (  3.690,  -7.350, 0.640),   # bricks  (full world only)
    (  7.350,   3.990, 0.640),   # bricks  (full world only)
    (  7.450,   5.200, 0.524),   # cabledrum  (full world only)
    (  4.300,   2.400, 0.110),   # cone
    (  4.200,  -1.400, 0.110),   # cone
    ( -4.300,   2.200, 0.110),   # cone
    ( -4.200,  -2.000, 0.110),   # cone
    (  2.300,   4.400, 0.110),   # cone  (full world only)
    ( -2.400,   4.300, 0.110),   # cone  (full world only)
    (  2.100,  -4.400, 0.110),   # cone  (full world only)
    ( -2.200,  -4.350, 0.110),   # cone  (full world only)
    ( -4.830,  -7.130, 1.688),   # container
    ( -7.200,  -5.850, 0.550),   # drums  (full world only)
    ( -7.280,  -4.220, 0.909),   # generator  (full world only)
    (  5.980,  -7.330, 0.420),   # mast  (full world only)
    ( -5.990,   7.410, 0.533),   # mixer  (full world only)
    (  4.720,   6.580, 2.046),   # office  (full world only)
    (  1.610,   6.700, 1.050),   # pile  (full world only)
    ( -6.800,   1.740, 0.950),   # pile
    ( -6.900,  -0.360, 0.850),   # pile  (full world only)
    ( -1.810,  -6.500, 1.250),   # pile
    (  6.300,  -2.020, 1.450),   # pile
    (  2.230,  -7.260, 0.904),   # pipes  (full world only)
    ( -7.500,   4.700, 1.718),   # rebar  (full world only)
    ( -4.520,   7.450, 0.739),   # sandbags  (full world only)
    (  0.300,   4.500, 0.090),   # sign  (full world only)
    (  0.200,  -4.500, 0.090),   # sign  (full world only)
    (  7.300,  -5.080, 1.399),   # timber  (full world only)
    (  7.500,   6.150, 0.354),   # toilet  (full world only)
]
